### ISSUE TITLE
Building shared libraries?

### ISSUE THREAD

**Issue by thierry-FreeBSD** [william-dawson/NTPoly#189]
Hello,
I’m packaging NTPoly for FreeBSD, and it builds fine, although I have to pass `-fallow-argument-mismatch` to Fortran FLAGS.
I have created a FreeBSD.cmake file under Targets, and I use it as CMAKE_TOOLCHAIN_FILE.
I put `set(TARGET_SUPPORTS_SHARED_LIBS Yes)` in it, like in Archer.cmake, but it only builds static libraries:
libNTPoly.a             libNTPolyCPP.a          libNTPolyWrapper.a
Grepping the code, it seems that SHARED_LIBS is never used: I’m missing something?

**Comment by william-dawson** [comment]
Thank you for your interest Thierry. I would definitely like to have a FreeBSD target. I believe the right way to generate dynamic libraries with `cmake` is to pass the option `-DBUILD_SHARED_LIBS=ON` to the `cmake` command. This will trigger the generation of `.so` or `.dylib` files. I can't remember why I set `TARGET_SUPPORTS_SHARED_LIBS` in the Archer configuration file, perhaps there was some issue caused by the cray compilers. Let me know if that works for you!

`-fallow-argument-mismatch` is indeed needed for newer version of gfortran. I think that I need to incorporate some kind of Fortran 90 binding for the blas/lapack routines in the future.

**Comment by thierry-FreeBSD** [comment]
Yes, `-DBUILD_SHARED_LIBS=ON` did the trick!

I’ve just added NTPoly to the FreeBSD ports tree: https://www.freshports.org/math/ntpoly/ .

**Comment by william-dawson** [comment]
Thanks for contributing!
